server:
  port: 8088
  tomcat:
    threads:
      max: 8000

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8

file-save-path: "D:/%s/"

