package com.open.ai.eros.ai.model.bean.vo.gpt;

import com.open.ai.eros.common.vo.ChatMessage;
import lombok.Data;

/**
 * A completion generated by OpenAI
 *
 * https://beta.openai.com/docs/api-reference/completions/create
 */
@Data
public class CompletionMessageChoice {
    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    ChatMessage message;

    /**
     * The reason why GPT stopped generating, for example "length".
     */
    String finish_reason;

    String text;
}
